### ISSUE TITLE
Astro 4

### ISSUE THREAD

**Issue by smalltimer** [alextim/astro-lib#62]
Hi,

I had the webmanifest working prefectly in Astro 3. I upgraded to Astro 4 and found the webmanifest does not work any more. There is always a residual .mjs file after a build. Besides `astro-webmanifest`, I am using `@astro/sitemap` and `astro-robots-txt` in my config. I was also generating an RSS feed using `@astrojs/rss`, which seems to have stopped working now. I am mentioning it to cover the off chance that it might be interacting with `astro-webmanifest`.

Cheers!

**Comment by MelihDarcanxyz** [comment]
I can't get `astro-webmanifest` working on `astro 4.3.5`. Getting an error like this:
```
[vite] Error when evaluating SSR module /mnt/STUFF/projects/neo-website/astro.config.ts: failed to import "astro-webmanifest"
|- Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
```
I have `sharp 0.33.2` installed, just to be clear.

**Comment by MelihDarcanxyz** [comment]
It somehow works now, with:

```yaml
astro:
    specifier: 4.14.3
    version: 4.14.3(@types/node@22.4.2)(rollup@4.21.0)(typescript@5.5.4)
```
